### ISSUE TITLE
Double enable message being sent when using /nightvision global add

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#12]
### issue-description

When you use /nightvision global add it sends 2 messages saying NightVision has been enabled for all players.

### Expected Behaviour

When using the command it should only send 1 message

### Debug Information

https://pastebin.com/CdfeYRs7

**Comment by OmegaWeaponDev** [comment]
Hi,
Thanks for reporting this. Will look into this in the next day or two when I have some free time.

OmegaWeaponDev

**Comment by OmegaWeaponDev** [comment]
Hi @baailey,

With OmegaVision 2.5.1 just being released, it should contain a fix for this issue. Please let me know if it is resolved.

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Fixed.
