### ISSUE TITLE
Introduce a config option or permission for who sees the global enable/disable message for all players

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#13]
### Enhancement Description

Currently, whenever `/nightvision global add` or `/nightvision global remove` is used, all players see the message in chat. I'd prefer this not be the case, and instead be toggleable via a permission or config option. I have tried setting the message as blank (just "") in the message.yml, however that just results in only the prefix being sent (possible bug?). 

### Functionality

It simply just won't send the message to normal players

**Comment by OmegaWeaponDev** [comment]
Hi,

This isn't a bad idea. I might see about adding this with the next update (in a couple days). I might also look into adding a check in to stop messages from sending if it is set to a blank message.

**Comment by baailey** [comment]
Either work really, I'd just rather the messages not be sent for players.

**Comment by OmegaWeaponDev** [comment]
What I am thinking, is to have an option to disable messages by setting them to blank, an also an option to send the global message to people with perms only.

**Comment by OmegaWeaponDev** [comment]
@baailey 
Hi,
I have just released version 2.5.1 which adds the permission `omegavision.nightvision.global.alert` which is now required for players to be able to receive the night vision applied/removed messages when night vision global command is used.

Please let me know if you're happy with it.

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Hello, this still notifies all players even when they don't have permission. I also tried setting the permission to false on a specific player, however that did not change default behaviour that I have encountered.

**Comment by baailey** [comment]
It seems /nightvision global remove doesn't actually disable nightvision for the player either. /nightvision global add **will** enable it though.

**Comment by OmegaWeaponDev** [comment]
Alright thanks, I'll look into it tomorrow and see what I can do and will let you know when I release and update to resolve them.

**Comment by OmegaWeaponDev** [comment]
Hi @baailey,

Please update to the latest version of OmegaVision (2.5.2) as this should resolve the issue with the messages still sending even without the permission and it also resolves the issue with the global remove command not working correctly.

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Hello, the original issue has been fixed, however this is still a problem:

> It seems /nightvision global remove doesn't actually disable nightvision for the player either. /nightvision global add **will** enable it though.

When I do the command it toggles on/off perfectly, but for other accounts, it doesn't disable.

**Comment by OmegaWeaponDev** [comment]
Are you sure you're using `/nv global remove` because I tested this an it was working perfectly.

**Comment by baailey** [comment]
The exact command I did was `/nightvision global remove`, unsure if that'd make a difference

**Comment by OmegaWeaponDev** [comment]
Hi @baailey 

Please update OmegaVision to version 2.5.3 as this should contain a fix for the bug.

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Fixed.
