### ISSUE TITLE
[Bug]: Incorrect message being sent when trying to enable NightVision after death

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#14]
### Issue Description

If a player does not have `omegavision.nightvision.keepondeath` set to `true`, but they have NightVision enabled upon death, they will be told their NightVision has been toggled off when trying to enable it upon respawn.

### Steps to Reproduce

1. Enable NightVision
2. Die
3. Try Enable NightVision, it will then tell you NightVision has been toggled off

### Expected Behaviour

It should enable NightVision and tell you it's been turned on.

### Debug Information

https://mcpaste.io/c44ee62040bd3014

**Comment by OmegaWeaponDev** [comment]
Hi @baailey 

This minor bug has been resolved with 2.5.4. Please update to receive the fix. 

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
This now sends a double enable message.

**Comment by OmegaWeaponDev** [comment]
A double message that is has been enabled or disabled?

**Comment by baailey** [comment]
Enabled. Disabled sends the proper 1 message.

**Comment by OmegaWeaponDev** [comment]
Hmm, this does not seem to be occurring for me. 

I removed the `omegavision.nightvision.keepondeath` permission, then enabled night vision then killed myself via console, and then enabled night vision again and it only sent the 1 message.

**Comment by baailey** [comment]
Correction; it only sends the double enable message when doing /nv [player]. Killing the player is not a necessary step.

**Comment by OmegaWeaponDev** [comment]
Version 2.5.6 will resolve this. 

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Fixed.
