### ISSUE TITLE
[Bug]: omegavision.nightvision.keepondeath doesn't actually work

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#15]
### Issue Description

A player who has permission to toggle NightVision will not keep NightVision upon death, even when they have the permission (config option set to true as well).

This is also the case for players who have the permission, but can only have NightVision if you yourself enable it for them (whether that be with /nv [player] or /nightvision global add).

### Steps to Reproduce

1. Give a player `omegavision.nightvision.keepondeath` 
2. Set `Keep_Night_Vision_On_Death` to true in the config
3. Have the player enable NightVision or enable it for them via one of the 2 methods listed previously
4. Do /kill [player]

### Expected Behaviour

The player should keep NightVision enabled

### Debug Information

https://mcpaste.io/c44ee62040bd3014

**Comment by OmegaWeaponDev** [comment]
Hi @baailey 

I can confirm this is an actual bug that I missed in testing. I am currently working a fix for this that should also resolve #14

**Comment by OmegaWeaponDev** [comment]
@baailey 

I have just released version 2.5.5 which contains a fix for this issue along with the issue stated in #14 so please test it out and let me know if it works.

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Fixed.
