### ISSUE TITLE
[Feature]: /nightvision global add/remove limited to online players

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#16]
### Issue Description

When trying to run /nightvision global add/remove through console, I am told I need to be a player to use this command. Unsure if the same issue will occur when a plugin tries to run the command, but if so, that seems like a rather important issue.

### Steps to Reproduce

1. Run /nightvision global add/remove through console

### Expected Behaviour

It should run the command as if it is being done by a player, and not be limited to only working when physically online.

### Debug Information

https://pastebin.com/ytfC2iNf

**Comment by OmegaWeaponDev** [comment]
This is more of me just not setting it up as a command that can be run from console. I'll make an update soon to make it a command that can be run from console and ingame.

**Comment by OmegaWeaponDev** [comment]
Hi @baailey 

I have just released a new update for OmegaVision which adds 1.18 support (requires Java 17 now) and it also includes using the night vision commands from Console!

Thanks,
OmegaWeaponDev
