### ISSUE TITLE
[Bug]: OmegaVision v2.5.10 generated an exception while executing task 385831

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#18]
### Issue Description

31.12 03:04:51 [Server] WARN [OmegaVision] Plugin OmegaVision v2.5.10 generated an exception while executing task 385831
31.12 03:04:51 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because the return value of "java.util.Map.get(Object)" is null
31.12 03:04:51 [Server] INFO at me.omegaweapondev.omegavision.utils.UserDataHandler.lambda$saveUserDataToFile$1(UserDataHandler.java:104) ~[OmegaVision-2.5.10.jar:?]
31.12 03:04:51 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-66]
31.12 03:04:51 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-66]
31.12 03:04:51 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-66]
31.12 03:04:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
31.12 03:04:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

### Steps to Reproduce

Not sure, a player disconnected and the error occured

### Expected Behaviour

No error, I guess.

### Debug Information

https://pastebin.com/kmbC21gs

**Comment by OmegaWeaponDev** [comment]
Hi @baailey 
[OmegaVision-2.5.11.zip](https://github.com/OmegaWeaponDev/OmegaVision/files/7795538/OmegaVision-2.5.11.zip)

Please try this version and see if it resolves the issue.
