### ISSUE TITLE
Error on PlayerJoinEvent

### ISSUE THREAD

**Issue by EnderGamingFilms** [OmegaWeaponDev/OmegaVision#2]
Version: Latest as of 6/14/2020
Minecraft Version: 1.15.2-R01-SNAPSHOT

Console Error:
https://pastebin.com/xQTBNDKm

**Comment by OmegaWeaponDev** [comment]
Hi EnderGamingFilms,

Thanks for reporting the error. I'll have a look into this and get it fixed as soon as possible. Could you please upload the contents of your config.yml

**Comment by EnderGamingFilms** [comment]
Config is the default, nothing has been touched.

**Comment by EnderGamingFilms** [comment]
Has this issue been resolved yet?

**Comment by OmegaWeaponDev** [comment]
Hi, I've not been able to resolve it yet as I've been very busy with my studies in real life. I should have a fix for this soon. As I'm currently redo a heap of the code which should fix this issue as well.

**Comment by OmegaWeaponDev** [comment]
Hi @EnderGamingFilms ,

I have hopefully fixed the issue with the latest update on spigot. https://www.spigotmc.org/resources/omegavision.73013/

Please update to this new version and let me know if it fixes the issue.

**Comment by EnderGamingFilms** [comment]
It appears to be fixed. Thanks.
