### ISSUE TITLE
Command messages in console

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#4]
Currently, when doing a command via console there is no 'confirmation' message that appears like there is when using it in-game.

I suggest that when turning night vision on for everyone, toggling it for a single player etc. that it should display the appropriate messages.yml per command.

**Comment by OmegaWeaponDev** [comment]
Hi,

Thanks for the feature request. I have released version 2.3.7 of OmegaVision that has included this feature as I liked the idea.

Thanks,
OmegaWeaponDev
