### ISSUE TITLE
Auto disable per world

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#5]
I suggest a config option that allows you to specify what world a player's night vision will auto-disable, possibly introduce a permission bypass as well. Or, instead of a config option, just have it auto-disable when they enter a world that the omegavision.toggle permission is not set in.

It'd be good to also introduce a messages.yml option for when nightvision is auto-disabled.

**Comment by OmegaWeaponDev** [comment]
Hi,

Thanks for the feature request. I have released version 2.3.7 of OmegaVision that has included this feature as I liked the idea. I have added the permission `omegavision.nightvision.worldbypass` that allows the person to bypass the auto disable for the worlds.
