### ISSUE TITLE
Console detects the wrong 'new version'

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#6]
When the plugin is enabled, it displays that the Current version is 2.3.6 and says the new version is 2.3.2, as seen [here](https://i.imgur.com/sOW4omX.png)

**Comment by OmegaWeaponDev** [comment]
This is more an issue with the updater for SpigotMC being slow. The update message will disappear once the SpigotMC updater catches up. I will look into implementing something to prevent it from happening later though. But for the time being, just have to wait until the updater catches up.

**Comment by baailey** [comment]
Ah, gotcha
