### ISSUE TITLE
Double message appears for the user you manually enable/disable Night Vision for

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#7]
If you do **/nv [user] on** a double message will appear for said user saying their Night Vision has been turned on. If you do **/nv [user] off** a double message will appear saying their Night Vision has been turned off. At first I thought maybe there was a copy-paste of messages in the messages.yml file, but it doesn't seem that there is a specific message for when another player manually toggles a users Night Vision.

**Comment by OmegaWeaponDev** [comment]
Hi,

This should have been resolved with version 2.3.7 

Please download the new version from spigot and get back to me if the message has been resolved.

Thanks,
OmegaWeaponDev

**Comment by OmegaWeaponDev** [comment]
Been 2 weeks without any contact, so assuming this has been resolved in the last update.
